/**
 * The single source of truth for every loader.
 * `id` must match a `.ldr--<id>` class in ./styles, and `cells` is how many
 * <span> children that variant's CSS expects.
 */
export const VARIANTS = [
  // ---- Spinners ----
  { id: "aurora", label: "Aurora", group: "Spinners", cells: 0 },
  { id: "spiral", label: "Spiral", group: "Spinners", cells: 0 },
  { id: "ring-dash", label: "Ring Dash", group: "Spinners", cells: 0 },
  { id: "ring-gap", label: "Ring Gap", group: "Spinners", cells: 0 },
  { id: "comet", label: "Comet", group: "Spinners", cells: 1 },
  { id: "arc-trio", label: "Arc Trio", group: "Spinners", cells: 3 },
  { id: "halo", label: "Halo", group: "Spinners", cells: 1 },
  { id: "sweep", label: "Sweep", group: "Spinners", cells: 0 },
  { id: "dot-ring", label: "Dot Ring", group: "Spinners", cells: 8 },
  { id: "petal", label: "Petal", group: "Spinners", cells: 8 },
  // ---- Dots ----
  { id: "wave", label: "Wave", group: "Dots", cells: 5 },
  { id: "orbit", label: "Orbit", group: "Dots", cells: 3 },
  { id: "bounce", label: "Bounce", group: "Dots", cells: 3 },
  { id: "fade-dots", label: "Fade Dots", group: "Dots", cells: 3 },
  { id: "pulse-dots", label: "Pulse Dots", group: "Dots", cells: 3 },
  { id: "typing", label: "Typing", group: "Dots", cells: 3 },
  { id: "chase", label: "Chase", group: "Dots", cells: 6 },
  { id: "snake", label: "Snake", group: "Dots", cells: 5 },
  { id: "swap", label: "Swap", group: "Dots", cells: 2 },
  { id: "juggle", label: "Juggle", group: "Dots", cells: 3 },
  // ---- Bars ----
  { id: "bars", label: "Bars", group: "Bars", cells: 5 },
  { id: "ladder", label: "Ladder", group: "Bars", cells: 4 },
  { id: "stretch", label: "Stretch", group: "Bars", cells: 5 },
  { id: "flip-bars", label: "Flip Bars", group: "Bars", cells: 5 },
  { id: "slide-bars", label: "Slide Bars", group: "Bars", cells: 3 },
  { id: "drop-bars", label: "Drop Bars", group: "Bars", cells: 5 },
  { id: "meter", label: "Meter", group: "Bars", cells: 5 },
  { id: "wave-bars", label: "Wave Bars", group: "Bars", cells: 7 },
  { id: "split-bars", label: "Split Bars", group: "Bars", cells: 4 },
  { id: "scan-bars", label: "Scan Bars", group: "Bars", cells: 6 },
  // ---- Shapes ----
  { id: "blob", label: "Blob", group: "Shapes", cells: 0 },
  { id: "cube", label: "Cube", group: "Shapes", cells: 2 },
  { id: "triangle", label: "Triangle", group: "Shapes", cells: 0 },
  { id: "hexagon", label: "Hexagon", group: "Shapes", cells: 0 },
  { id: "diamond", label: "Diamond", group: "Shapes", cells: 0 },
  { id: "star", label: "Star", group: "Shapes", cells: 0 },
  { id: "squircle", label: "Squircle", group: "Shapes", cells: 0 },
  { id: "folding", label: "Folding", group: "Shapes", cells: 4 },
  { id: "pentagon", label: "Pentagon", group: "Shapes", cells: 0 },
  { id: "shape-shift", label: "Shape Shift", group: "Shapes", cells: 0 },
  // ---- Progress ----
  { id: "bar", label: "Bar", group: "Progress", cells: 0 },
  { id: "bar-stripes", label: "Bar Stripes", group: "Progress", cells: 0 },
  { id: "bar-dual", label: "Bar Dual", group: "Progress", cells: 0 },
  { id: "bar-segments", label: "Bar Segments", group: "Progress", cells: 5 },
  { id: "bar-pill", label: "Bar Pill", group: "Progress", cells: 0 },
  { id: "bar-glow", label: "Bar Glow", group: "Progress", cells: 0 },
  { id: "bar-wave", label: "Bar Wave", group: "Progress", cells: 0 },
  { id: "bar-dots", label: "Bar Dots", group: "Progress", cells: 5 },
  { id: "bar-snake", label: "Bar Snake", group: "Progress", cells: 0 },
  { id: "bar-fill", label: "Bar Fill", group: "Progress", cells: 0 },
  // ---- Grids ----
  { id: "grid", label: "Grid", group: "Grids", cells: 9 },
  { id: "checker", label: "Checker", group: "Grids", cells: 9 },
  { id: "cascade", label: "Cascade", group: "Grids", cells: 9 },
  { id: "tiles", label: "Tiles", group: "Grids", cells: 9 },
  { id: "pixel", label: "Pixel", group: "Grids", cells: 16 },
  { id: "matrix", label: "Matrix", group: "Grids", cells: 9 },
  { id: "mosaic", label: "Mosaic", group: "Grids", cells: 9 },
  { id: "ripple-grid", label: "Ripple Grid", group: "Grids", cells: 9 },
  { id: "domino", label: "Domino", group: "Grids", cells: 9 },
  { id: "sparkle", label: "Sparkle", group: "Grids", cells: 9 },
  // ---- Pulses ----
  { id: "rings", label: "Rings", group: "Pulses", cells: 3 },
  { id: "radar", label: "Radar", group: "Pulses", cells: 2 },
  { id: "sonar", label: "Sonar", group: "Pulses", cells: 3 },
  { id: "echo", label: "Echo", group: "Pulses", cells: 3 },
  { id: "shockwave", label: "Shockwave", group: "Pulses", cells: 2 },
  { id: "bloom", label: "Bloom", group: "Pulses", cells: 3 },
  { id: "droplet", label: "Droplet", group: "Pulses", cells: 2 },
  { id: "concentric", label: "Concentric", group: "Pulses", cells: 3 },
  { id: "aura", label: "Aura", group: "Pulses", cells: 1 },
  { id: "beacon", label: "Beacon", group: "Pulses", cells: 2 },
  // ---- Organic ----
  { id: "heart", label: "Heart", group: "Organic", cells: 0 },
  { id: "moon", label: "Moon", group: "Organic", cells: 0 },
  { id: "sun", label: "Sun", group: "Organic", cells: 8 },
  { id: "flame", label: "Flame", group: "Organic", cells: 0 },
  { id: "bubble", label: "Bubble", group: "Organic", cells: 3 },
  { id: "jelly", label: "Jelly", group: "Organic", cells: 0 },
  { id: "spring", label: "Spring", group: "Organic", cells: 0 },
  { id: "float", label: "Float", group: "Organic", cells: 1 },
  { id: "leaf", label: "Leaf", group: "Organic", cells: 0 },
  { id: "windmill", label: "Windmill", group: "Organic", cells: 4 },
  // ---- Skeletons ----
  { id: "shimmer", label: "Shimmer", group: "Skeletons", cells: 0 },
  { id: "sk-text", label: "Text", group: "Skeletons", cells: 3 },
  { id: "sk-card", label: "Card", group: "Skeletons", cells: 3 },
  { id: "sk-avatar", label: "Avatar", group: "Skeletons", cells: 2 },
  { id: "sk-image", label: "Image", group: "Skeletons", cells: 0 },
  { id: "sk-list", label: "List", group: "Skeletons", cells: 3 },
  { id: "sk-table", label: "Table", group: "Skeletons", cells: 4 },
  { id: "sk-chip", label: "Chips", group: "Skeletons", cells: 3 },
  { id: "sk-paragraph", label: "Paragraph", group: "Skeletons", cells: 4 },
  { id: "sk-media", label: "Media", group: "Skeletons", cells: 2 },
  // ---- Dimensional ----
  { id: "helix", label: "Helix", group: "Dimensional", cells: 8 },
  { id: "pendulum", label: "Pendulum", group: "Dimensional", cells: 5 },
  { id: "atom", label: "Atom", group: "Dimensional", cells: 3 },
  { id: "gyro", label: "Gyro", group: "Dimensional", cells: 3 },
  { id: "coil", label: "Coil", group: "Dimensional", cells: 5 },
  { id: "vortex", label: "Vortex", group: "Dimensional", cells: 4 },
  { id: "prism", label: "Prism", group: "Dimensional", cells: 3 },
  { id: "torus", label: "Torus", group: "Dimensional", cells: 0 },
  { id: "cylinder", label: "Cylinder", group: "Dimensional", cells: 4 },
  { id: "galaxy", label: "Galaxy", group: "Dimensional", cells: 6 },
  // ---- Neon ----
  { id: "neon-ring", label: "Neon Ring", group: "Neon", cells: 0 },
  { id: "neon-pulse", label: "Neon Pulse", group: "Neon", cells: 0 },
  { id: "neon-tube", label: "Neon Tube", group: "Neon", cells: 0 },
  { id: "neon-sign", label: "Neon Sign", group: "Neon", cells: 4 },
  { id: "laser", label: "Laser", group: "Neon", cells: 0 },
  { id: "light-trail", label: "Light Trail", group: "Neon", cells: 0 },
  { id: "neon-arc", label: "Neon Arc", group: "Neon", cells: 0 },
  { id: "plasma", label: "Plasma", group: "Neon", cells: 0 },
  { id: "strobe", label: "Strobe", group: "Neon", cells: 3 },
  { id: "glow-dots", label: "Glow Dots", group: "Neon", cells: 5 },
  { id: "retro-grid", label: "Retro Grid", group: "Neon", cells: 0 },
  { id: "firefly", label: "Firefly", group: "Neon", cells: 5 },
  // ---- Liquid ----
  { id: "liquid-fill", label: "Liquid Fill", group: "Liquid", cells: 2 },
  { id: "drip", label: "Drip", group: "Liquid", cells: 1 },
  { id: "metaball", label: "Metaball", group: "Liquid", cells: 2 },
  { id: "wave-tank", label: "Wave Tank", group: "Liquid", cells: 2 },
  { id: "ripple-pool", label: "Ripple Pool", group: "Liquid", cells: 3 },
  { id: "mercury", label: "Mercury", group: "Liquid", cells: 0 },
  { id: "lava", label: "Lava", group: "Liquid", cells: 3 },
  { id: "ink", label: "Ink", group: "Liquid", cells: 3 },
  { id: "splash", label: "Splash", group: "Liquid", cells: 3 },
  { id: "whirl", label: "Whirl", group: "Liquid", cells: 0 },
  { id: "pour", label: "Pour", group: "Liquid", cells: 2 },
  // ---- Glitch ----
  { id: "glitch-block", label: "Glitch Block", group: "Glitch", cells: 0 },
  { id: "glitch-text", label: "Glitch Text", group: "Glitch", cells: 3 },
  { id: "rgb-split", label: "RGB Split", group: "Glitch", cells: 3 },
  { id: "scanlines", label: "Scanlines", group: "Glitch", cells: 0 },
  { id: "static-noise", label: "Static", group: "Glitch", cells: 0 },
  { id: "datamosh", label: "Datamosh", group: "Glitch", cells: 5 },
  { id: "corrupt-bar", label: "Corrupt Bar", group: "Glitch", cells: 0 },
  { id: "signal-loss", label: "Signal Loss", group: "Glitch", cells: 4 },
  { id: "vhs", label: "VHS", group: "Glitch", cells: 0 },
  { id: "pixel-drift", label: "Pixel Drift", group: "Glitch", cells: 9 },
  { id: "terminal", label: "Terminal", group: "Glitch", cells: 2 },
  // ---- Particles ----
  { id: "confetti", label: "Confetti", group: "Particles", cells: 8 },
  { id: "firework", label: "Firework", group: "Particles", cells: 8 },
  { id: "snow", label: "Snow", group: "Particles", cells: 6 },
  { id: "embers", label: "Embers", group: "Particles", cells: 5 },
  { id: "starfield", label: "Starfield", group: "Particles", cells: 8 },
  { id: "dust", label: "Dust", group: "Particles", cells: 7 },
  { id: "burst", label: "Burst", group: "Particles", cells: 6 },
  { id: "swarm", label: "Swarm", group: "Particles", cells: 7 },
  { id: "rain", label: "Rain", group: "Particles", cells: 6 },
  { id: "magnet", label: "Magnet", group: "Particles", cells: 7 },
  { id: "nebula", label: "Nebula", group: "Particles", cells: 6 },
  // ---- Futuristic ----
  { id: "hud-ring", label: "HUD Ring", group: "Futuristic", cells: 2 },
  { id: "reactor", label: "Reactor", group: "Futuristic", cells: 3 },
  { id: "hologram", label: "Hologram", group: "Futuristic", cells: 3 },
  { id: "warp", label: "Warp", group: "Futuristic", cells: 4 },
  { id: "targeting", label: "Targeting", group: "Futuristic", cells: 4 },
  { id: "circuit", label: "Circuit", group: "Futuristic", cells: 3 },
  { id: "barcode", label: "Barcode", group: "Futuristic", cells: 0 },
  { id: "quantum", label: "Quantum", group: "Futuristic", cells: 6 },
  { id: "portal", label: "Portal", group: "Futuristic", cells: 0 },
  { id: "shield", label: "Shield", group: "Futuristic", cells: 2 },
  { id: "satellite", label: "Satellite", group: "Futuristic", cells: 3 },
  { id: "teleport", label: "Teleport", group: "Futuristic", cells: 6 },
  // ---- Elastic ----
  { id: "rubber-band", label: "Rubber Band", group: "Elastic", cells: 1 },
  { id: "bungee", label: "Bungee", group: "Elastic", cells: 1 },
  { id: "trampoline", label: "Trampoline", group: "Elastic", cells: 1 },
  { id: "wobble", label: "Wobble", group: "Elastic", cells: 0 },
  { id: "pogo", label: "Pogo", group: "Elastic", cells: 1 },
  { id: "elastic-bar", label: "Elastic Bar", group: "Elastic", cells: 0 },
  { id: "catapult", label: "Catapult", group: "Elastic", cells: 1 },
  { id: "yo-yo", label: "Yo-yo", group: "Elastic", cells: 1 },
  { id: "elastic-ring", label: "Elastic Ring", group: "Elastic", cells: 0 },
  { id: "snap-dots", label: "Snap Dots", group: "Elastic", cells: 2 },
  { id: "chain", label: "Chain", group: "Elastic", cells: 5 },
  // ---- Minimal ----
  { id: "hairline", label: "Hairline", group: "Minimal", cells: 0 },
  { id: "tick", label: "Tick", group: "Minimal", cells: 0 },
  { id: "quarter", label: "Quarter", group: "Minimal", cells: 0 },
  { id: "dot-fade", label: "Dot Fade", group: "Minimal", cells: 0 },
  { id: "underline", label: "Underline", group: "Minimal", cells: 0 },
  { id: "pill-swap", label: "Pill Swap", group: "Minimal", cells: 0 },
  { id: "bracket", label: "Bracket", group: "Minimal", cells: 2 },
  { id: "slash", label: "Slash", group: "Minimal", cells: 0 },
  { id: "micro-dots", label: "Micro Dots", group: "Minimal", cells: 3 },
  { id: "ring-thin", label: "Ring Thin", group: "Minimal", cells: 0 },
  { id: "crosshair", label: "Crosshair", group: "Minimal", cells: 0 },
  // ---- Gradient ----
  { id: "mesh", label: "Mesh", group: "Gradient", cells: 0 },
  { id: "hue-ring", label: "Hue Ring", group: "Gradient", cells: 0 },
  { id: "gradient-orb", label: "Gradient Orb", group: "Gradient", cells: 0 },
  { id: "chroma", label: "Chroma", group: "Gradient", cells: 3 },
  { id: "ombre", label: "Ombré", group: "Gradient", cells: 6 },
  { id: "iridescent", label: "Iridescent", group: "Gradient", cells: 0 },
  { id: "sunrise", label: "Sunrise", group: "Gradient", cells: 0 },
  { id: "refract", label: "Refract", group: "Gradient", cells: 3 },
  { id: "gradient-border", label: "Gradient Border", group: "Gradient", cells: 0 },
  { id: "color-cycle", label: "Color Cycle", group: "Gradient", cells: 0 },
  { id: "northern", label: "Northern", group: "Gradient", cells: 4 },
  // ---- Kinetic ----
  { id: "gears", label: "Gears", group: "Kinetic", cells: 2 },
  { id: "metronome", label: "Metronome", group: "Kinetic", cells: 1 },
  { id: "hourglass", label: "Hourglass", group: "Kinetic", cells: 3 },
  { id: "piston", label: "Piston", group: "Kinetic", cells: 1 },
  { id: "carousel", label: "Carousel", group: "Kinetic", cells: 5 },
  { id: "clockwork", label: "Clockwork", group: "Kinetic", cells: 3 },
  { id: "abacus", label: "Abacus", group: "Kinetic", cells: 3 },
  { id: "conveyor", label: "Conveyor", group: "Kinetic", cells: 3 },
  { id: "pie", label: "Pie", group: "Kinetic", cells: 0 },
  { id: "seesaw", label: "Seesaw", group: "Kinetic", cells: 1 },
  { id: "roller", label: "Roller", group: "Kinetic", cells: 2 },
  // ---- Premium ----
  { id: "logo-morph", label: "Logo Morph", group: "Premium", cells: 3 },
  { id: "card-stack", label: "Card Stack", group: "Premium", cells: 3 },
  { id: "progress-ring", label: "Progress Ring", group: "Premium", cells: 1 },
  { id: "pill-progress", label: "Pill Progress", group: "Premium", cells: 0 },
  { id: "glass-ring", label: "Glass Ring", group: "Premium", cells: 0 },
  { id: "orbit-avatar", label: "Orbit Avatar", group: "Premium", cells: 5 },
  { id: "checklist", label: "Checklist", group: "Premium", cells: 3 },
  { id: "upload-cloud", label: "Upload Cloud", group: "Premium", cells: 3 },
  { id: "sync", label: "Sync", group: "Premium", cells: 2 },
  { id: "steps", label: "Steps", group: "Premium", cells: 4 },
  { id: "spark-line", label: "Spark Line", group: "Premium", cells: 2 },
] as const;

export const GROUPS = [
  { name: "Spinners", description: "Rings and arcs — the classic shape, modernised." },
  { name: "Dots", description: "Small, quiet, and good inline with text." },
  { name: "Bars", description: "Equalizer-style motion with a strong rhythm." },
  { name: "Shapes", description: "Geometry that morphs, folds, and turns." },
  { name: "Progress", description: "Wide, indeterminate tracks for page and upload states." },
  { name: "Grids", description: "Cell fields that pulse, flip, and cascade." },
  { name: "Pulses", description: "Expanding rings for live, waiting, or listening states." },
  { name: "Organic", description: "Playful, physical motion with personality." },
  { name: "Skeletons", description: "Content-shaped placeholders — use these over spinners for page loads." },
  { name: "Dimensional", description: "Depth, 3D rotation, and orbital motion." },
  { name: "Neon", description: "Light that hums, blooms, and flickers alight." },
  { name: "Liquid", description: "Fluid behaviour — filling, pouring, rippling, merging." },
  { name: "Glitch", description: "Digital damage: tearing, static, dropout, corruption." },
  { name: "Particles", description: "Fields of small things falling, bursting, drifting, swarming." },
  { name: "Futuristic", description: "Reticles, reactors, and hardware that does not exist yet." },
  { name: "Elastic", description: "Spring physics with genuine overshoot and recoil." },
  { name: "Minimal", description: "Quiet motion for dense UI, toolbars, and inline text." },
  { name: "Gradient", description: "Colour itself is the animation." },
  { name: "Kinetic", description: "Mechanisms — gears, cranks, belts, beams, and escapements." },
  { name: "Premium", description: "Product-grade motion for onboarding, uploads, and sync." },
] as const;

export type LoaderVariant = (typeof VARIANTS)[number]["id"];
export type LoaderGroup = (typeof GROUPS)[number]["name"];
export type VariantMeta = (typeof VARIANTS)[number];
