/**
 * The single source of truth for every loader.
 * `id` must match a `.ldr--<id>` class in ./styles, and `cells` is how many
 * <span> children that variant's CSS expects.
 */
export const VARIANTS = [
  // ---- Spinners ----
  { id: "aurora", label: "Aurora", group: "Spinners", cells: 0 },
  { id: "spiral", label: "Spiral", group: "Spinners", cells: 0 },
  { id: "ring-dash", label: "Ring Dash", group: "Spinners", cells: 0 },
  { id: "ring-gap", label: "Ring Gap", group: "Spinners", cells: 0 },
  { id: "comet", label: "Comet", group: "Spinners", cells: 1 },
  { id: "arc-trio", label: "Arc Trio", group: "Spinners", cells: 3 },
  { id: "halo", label: "Halo", group: "Spinners", cells: 1 },
  { id: "sweep", label: "Sweep", group: "Spinners", cells: 0 },
  { id: "dot-ring", label: "Dot Ring", group: "Spinners", cells: 8 },
  { id: "petal", label: "Petal", group: "Spinners", cells: 8 },
  // ---- Dots ----
  { id: "wave", label: "Wave", group: "Dots", cells: 5 },
  { id: "orbit", label: "Orbit", group: "Dots", cells: 3 },
  { id: "bounce", label: "Bounce", group: "Dots", cells: 3 },
  { id: "fade-dots", label: "Fade Dots", group: "Dots", cells: 3 },
  { id: "pulse-dots", label: "Pulse Dots", group: "Dots", cells: 3 },
  { id: "typing", label: "Typing", group: "Dots", cells: 3 },
  { id: "chase", label: "Chase", group: "Dots", cells: 6 },
  { id: "snake", label: "Snake", group: "Dots", cells: 5 },
  { id: "swap", label: "Swap", group: "Dots", cells: 2 },
  { id: "juggle", label: "Juggle", group: "Dots", cells: 3 },
  // ---- Bars ----
  { id: "bars", label: "Bars", group: "Bars", cells: 5 },
  { id: "ladder", label: "Ladder", group: "Bars", cells: 4 },
  { id: "stretch", label: "Stretch", group: "Bars", cells: 5 },
  { id: "flip-bars", label: "Flip Bars", group: "Bars", cells: 5 },
  { id: "slide-bars", label: "Slide Bars", group: "Bars", cells: 3 },
  { id: "drop-bars", label: "Drop Bars", group: "Bars", cells: 5 },
  { id: "meter", label: "Meter", group: "Bars", cells: 5 },
  { id: "wave-bars", label: "Wave Bars", group: "Bars", cells: 7 },
  { id: "split-bars", label: "Split Bars", group: "Bars", cells: 4 },
  { id: "scan-bars", label: "Scan Bars", group: "Bars", cells: 6 },
  // ---- Shapes ----
  { id: "blob", label: "Blob", group: "Shapes", cells: 0 },
  { id: "cube", label: "Cube", group: "Shapes", cells: 2 },
  { id: "triangle", label: "Triangle", group: "Shapes", cells: 0 },
  { id: "hexagon", label: "Hexagon", group: "Shapes", cells: 0 },
  { id: "diamond", label: "Diamond", group: "Shapes", cells: 0 },
  { id: "star", label: "Star", group: "Shapes", cells: 0 },
  { id: "squircle", label: "Squircle", group: "Shapes", cells: 0 },
  { id: "folding", label: "Folding", group: "Shapes", cells: 4 },
  { id: "pentagon", label: "Pentagon", group: "Shapes", cells: 0 },
  { id: "shape-shift", label: "Shape Shift", group: "Shapes", cells: 0 },
  // ---- Progress ----
  { id: "bar", label: "Bar", group: "Progress", cells: 0 },
  { id: "bar-stripes", label: "Bar Stripes", group: "Progress", cells: 0 },
  { id: "bar-dual", label: "Bar Dual", group: "Progress", cells: 0 },
  { id: "bar-segments", label: "Bar Segments", group: "Progress", cells: 5 },
  { id: "bar-pill", label: "Bar Pill", group: "Progress", cells: 0 },
  { id: "bar-glow", label: "Bar Glow", group: "Progress", cells: 0 },
  { id: "bar-wave", label: "Bar Wave", group: "Progress", cells: 0 },
  { id: "bar-dots", label: "Bar Dots", group: "Progress", cells: 5 },
  { id: "bar-snake", label: "Bar Snake", group: "Progress", cells: 0 },
  { id: "bar-fill", label: "Bar Fill", group: "Progress", cells: 0 },
  // ---- Grids ----
  { id: "grid", label: "Grid", group: "Grids", cells: 9 },
  { id: "checker", label: "Checker", group: "Grids", cells: 9 },
  { id: "cascade", label: "Cascade", group: "Grids", cells: 9 },
  { id: "tiles", label: "Tiles", group: "Grids", cells: 9 },
  { id: "pixel", label: "Pixel", group: "Grids", cells: 16 },
  { id: "matrix", label: "Matrix", group: "Grids", cells: 9 },
  { id: "mosaic", label: "Mosaic", group: "Grids", cells: 9 },
  { id: "ripple-grid", label: "Ripple Grid", group: "Grids", cells: 9 },
  { id: "domino", label: "Domino", group: "Grids", cells: 9 },
  { id: "sparkle", label: "Sparkle", group: "Grids", cells: 9 },
  // ---- Pulses ----
  { id: "rings", label: "Rings", group: "Pulses", cells: 3 },
  { id: "radar", label: "Radar", group: "Pulses", cells: 2 },
  { id: "sonar", label: "Sonar", group: "Pulses", cells: 3 },
  { id: "echo", label: "Echo", group: "Pulses", cells: 3 },
  { id: "shockwave", label: "Shockwave", group: "Pulses", cells: 2 },
  { id: "bloom", label: "Bloom", group: "Pulses", cells: 3 },
  { id: "droplet", label: "Droplet", group: "Pulses", cells: 2 },
  { id: "concentric", label: "Concentric", group: "Pulses", cells: 3 },
  { id: "aura", label: "Aura", group: "Pulses", cells: 1 },
  { id: "beacon", label: "Beacon", group: "Pulses", cells: 2 },
  // ---- Organic ----
  { id: "heart", label: "Heart", group: "Organic", cells: 0 },
  { id: "moon", label: "Moon", group: "Organic", cells: 0 },
  { id: "sun", label: "Sun", group: "Organic", cells: 8 },
  { id: "flame", label: "Flame", group: "Organic", cells: 0 },
  { id: "bubble", label: "Bubble", group: "Organic", cells: 3 },
  { id: "jelly", label: "Jelly", group: "Organic", cells: 0 },
  { id: "spring", label: "Spring", group: "Organic", cells: 0 },
  { id: "float", label: "Float", group: "Organic", cells: 1 },
  { id: "leaf", label: "Leaf", group: "Organic", cells: 0 },
  { id: "windmill", label: "Windmill", group: "Organic", cells: 4 },
  // ---- Skeletons ----
  { id: "shimmer", label: "Shimmer", group: "Skeletons", cells: 0 },
  { id: "sk-text", label: "Text", group: "Skeletons", cells: 3 },
  { id: "sk-card", label: "Card", group: "Skeletons", cells: 3 },
  { id: "sk-avatar", label: "Avatar", group: "Skeletons", cells: 2 },
  { id: "sk-image", label: "Image", group: "Skeletons", cells: 0 },
  { id: "sk-list", label: "List", group: "Skeletons", cells: 3 },
  { id: "sk-table", label: "Table", group: "Skeletons", cells: 4 },
  { id: "sk-chip", label: "Chips", group: "Skeletons", cells: 3 },
  { id: "sk-paragraph", label: "Paragraph", group: "Skeletons", cells: 4 },
  { id: "sk-media", label: "Media", group: "Skeletons", cells: 2 },
  // ---- Dimensional ----
  { id: "helix", label: "Helix", group: "Dimensional", cells: 8 },
  { id: "pendulum", label: "Pendulum", group: "Dimensional", cells: 5 },
  { id: "atom", label: "Atom", group: "Dimensional", cells: 3 },
  { id: "gyro", label: "Gyro", group: "Dimensional", cells: 3 },
  { id: "coil", label: "Coil", group: "Dimensional", cells: 5 },
  { id: "vortex", label: "Vortex", group: "Dimensional", cells: 4 },
  { id: "prism", label: "Prism", group: "Dimensional", cells: 3 },
  { id: "torus", label: "Torus", group: "Dimensional", cells: 0 },
  { id: "cylinder", label: "Cylinder", group: "Dimensional", cells: 4 },
  { id: "galaxy", label: "Galaxy", group: "Dimensional", cells: 6 },
] as const;

export const GROUPS = [
  { name: "Spinners", description: "Rings and arcs — the classic shape, modernised." },
  { name: "Dots", description: "Small, quiet, and good inline with text." },
  { name: "Bars", description: "Equalizer-style motion with a strong rhythm." },
  { name: "Shapes", description: "Geometry that morphs, folds, and turns." },
  { name: "Progress", description: "Wide, indeterminate tracks for page and upload states." },
  { name: "Grids", description: "Cell fields that pulse, flip, and cascade." },
  { name: "Pulses", description: "Expanding rings for live, waiting, or listening states." },
  { name: "Organic", description: "Playful, physical motion with personality." },
  { name: "Skeletons", description: "Content-shaped placeholders — use these over spinners for page loads." },
  { name: "Dimensional", description: "Depth, 3D rotation, and orbital motion." },
] as const;

export type LoaderVariant = (typeof VARIANTS)[number]["id"];
export type LoaderGroup = (typeof GROUPS)[number]["name"];
export type VariantMeta = (typeof VARIANTS)[number];
