/**
 * The single source of truth for every loader.
 * `id` must match a `.ldr--<id>` class in ./styles, and `cells` is how many
 * <span> children that variant's CSS expects.
 */
export const VARIANTS = [
  // ---- Spinners ----
  { id: "aurora", label: "Aurora", group: "Spinners", cells: 0 },
  { id: "spiral", label: "Spiral", group: "Spinners", cells: 0 },
  { id: "ring-dash", label: "Ring Dash", group: "Spinners", cells: 0 },
  { id: "ring-gap", label: "Ring Gap", group: "Spinners", cells: 0 },
  { id: "comet", label: "Comet", group: "Spinners", cells: 1 },
  { id: "arc-trio", label: "Arc Trio", group: "Spinners", cells: 3 },
  { id: "halo", label: "Halo", group: "Spinners", cells: 1 },
  { id: "sweep", label: "Sweep", group: "Spinners", cells: 0 },
  { id: "dot-ring", label: "Dot Ring", group: "Spinners", cells: 8 },
  { id: "petal", label: "Petal", group: "Spinners", cells: 8 },
  // ---- Dots ----
  { id: "wave", label: "Wave", group: "Dots", cells: 5 },
  { id: "orbit", label: "Orbit", group: "Dots", cells: 3 },
  { id: "bounce", label: "Bounce", group: "Dots", cells: 3 },
  { id: "fade-dots", label: "Fade Dots", group: "Dots", cells: 3 },
  { id: "pulse-dots", label: "Pulse Dots", group: "Dots", cells: 3 },
  { id: "typing", label: "Typing", group: "Dots", cells: 3 },
  { id: "chase", label: "Chase", group: "Dots", cells: 6 },
  { id: "snake", label: "Snake", group: "Dots", cells: 5 },
  { id: "swap", label: "Swap", group: "Dots", cells: 2 },
  { id: "juggle", label: "Juggle", group: "Dots", cells: 3 },
  // ---- Bars ----
  { id: "bars", label: "Bars", group: "Bars", cells: 5 },
  { id: "ladder", label: "Ladder", group: "Bars", cells: 4 },
  { id: "stretch", label: "Stretch", group: "Bars", cells: 5 },
  { id: "flip-bars", label: "Flip Bars", group: "Bars", cells: 5 },
  { id: "slide-bars", label: "Slide Bars", group: "Bars", cells: 3 },
  { id: "drop-bars", label: "Drop Bars", group: "Bars", cells: 5 },
  { id: "meter", label: "Meter", group: "Bars", cells: 5 },
  { id: "wave-bars", label: "Wave Bars", group: "Bars", cells: 7 },
  { id: "split-bars", label: "Split Bars", group: "Bars", cells: 4 },
  { id: "scan-bars", label: "Scan Bars", group: "Bars", cells: 6 },
  // ---- Shapes ----
  { id: "blob", label: "Blob", group: "Shapes", cells: 0 },
  { id: "cube", label: "Cube", group: "Shapes", cells: 2 },
  { id: "triangle", label: "Triangle", group: "Shapes", cells: 0 },
  { id: "hexagon", label: "Hexagon", group: "Shapes", cells: 0 },
  { id: "diamond", label: "Diamond", group: "Shapes", cells: 0 },
  { id: "star", label: "Star", group: "Shapes", cells: 0 },
  { id: "squircle", label: "Squircle", group: "Shapes", cells: 0 },
  { id: "folding", label: "Folding", group: "Shapes", cells: 4 },
  { id: "pentagon", label: "Pentagon", group: "Shapes", cells: 0 },
  { id: "shape-shift", label: "Shape Shift", group: "Shapes", cells: 0 },
  // ---- Progress ----
  { id: "bar", label: "Bar", group: "Progress", cells: 0 },
  { id: "bar-stripes", label: "Bar Stripes", group: "Progress", cells: 0 },
  { id: "bar-dual", label: "Bar Dual", group: "Progress", cells: 0 },
  { id: "bar-segments", label: "Bar Segments", group: "Progress", cells: 5 },
  { id: "bar-pill", label: "Bar Pill", group: "Progress", cells: 0 },
  { id: "bar-glow", label: "Bar Glow", group: "Progress", cells: 0 },
  { id: "bar-wave", label: "Bar Wave", group: "Progress", cells: 0 },
  { id: "bar-dots", label: "Bar Dots", group: "Progress", cells: 5 },
  { id: "bar-snake", label: "Bar Snake", group: "Progress", cells: 0 },
  { id: "bar-fill", label: "Bar Fill", group: "Progress", cells: 0 },
  // ---- Grids ----
  { id: "grid", label: "Grid", group: "Grids", cells: 9 },
  { id: "checker", label: "Checker", group: "Grids", cells: 9 },
  { id: "cascade", label: "Cascade", group: "Grids", cells: 9 },
  { id: "tiles", label: "Tiles", group: "Grids", cells: 9 },
  { id: "pixel", label: "Pixel", group: "Grids", cells: 16 },
  { id: "matrix", label: "Matrix", group: "Grids", cells: 9 },
  { id: "mosaic", label: "Mosaic", group: "Grids", cells: 9 },
  { id: "ripple-grid", label: "Ripple Grid", group: "Grids", cells: 9 },
  { id: "domino", label: "Domino", group: "Grids", cells: 9 },
  { id: "sparkle", label: "Sparkle", group: "Grids", cells: 9 },
  // ---- Pulses ----
  { id: "rings", label: "Rings", group: "Pulses", cells: 3 },
  { id: "radar", label: "Radar", group: "Pulses", cells: 2 },
  { id: "sonar", label: "Sonar", group: "Pulses", cells: 3 },
  { id: "echo", label: "Echo", group: "Pulses", cells: 3 },
  { id: "shockwave", label: "Shockwave", group: "Pulses", cells: 2 },
  { id: "bloom", label: "Bloom", group: "Pulses", cells: 3 },
  { id: "droplet", label: "Droplet", group: "Pulses", cells: 2 },
  { id: "concentric", label: "Concentric", group: "Pulses", cells: 3 },
  { id: "aura", label: "Aura", group: "Pulses", cells: 1 },
  { id: "beacon", label: "Beacon", group: "Pulses", cells: 2 },
  // ---- Organic ----
  { id: "heart", label: "Heart", group: "Organic", cells: 0 },
  { id: "moon", label: "Moon", group: "Organic", cells: 0 },
  { id: "sun", label: "Sun", group: "Organic", cells: 8 },
  { id: "flame", label: "Flame", group: "Organic", cells: 0 },
  { id: "bubble", label: "Bubble", group: "Organic", cells: 3 },
  { id: "jelly", label: "Jelly", group: "Organic", cells: 0 },
  { id: "spring", label: "Spring", group: "Organic", cells: 0 },
  { id: "float", label: "Float", group: "Organic", cells: 1 },
  { id: "leaf", label: "Leaf", group: "Organic", cells: 0 },
  { id: "windmill", label: "Windmill", group: "Organic", cells: 4 },
  // ---- Skeletons ----
  { id: "shimmer", label: "Shimmer", group: "Skeletons", cells: 0 },
  { id: "sk-text", label: "Text", group: "Skeletons", cells: 3 },
  { id: "sk-card", label: "Card", group: "Skeletons", cells: 3 },
  { id: "sk-avatar", label: "Avatar", group: "Skeletons", cells: 2 },
  { id: "sk-image", label: "Image", group: "Skeletons", cells: 0 },
  { id: "sk-list", label: "List", group: "Skeletons", cells: 3 },
  { id: "sk-table", label: "Table", group: "Skeletons", cells: 4 },
  { id: "sk-chip", label: "Chips", group: "Skeletons", cells: 3 },
  { id: "sk-paragraph", label: "Paragraph", group: "Skeletons", cells: 4 },
  { id: "sk-media", label: "Media", group: "Skeletons", cells: 2 },
  // ---- Dimensional ----
  { id: "helix", label: "Helix", group: "Dimensional", cells: 8 },
  { id: "pendulum", label: "Pendulum", group: "Dimensional", cells: 5 },
  { id: "atom", label: "Atom", group: "Dimensional", cells: 3 },
  { id: "gyro", label: "Gyro", group: "Dimensional", cells: 3 },
  { id: "coil", label: "Coil", group: "Dimensional", cells: 5 },
  { id: "vortex", label: "Vortex", group: "Dimensional", cells: 4 },
  { id: "prism", label: "Prism", group: "Dimensional", cells: 3 },
  { id: "torus", label: "Torus", group: "Dimensional", cells: 0 },
  { id: "cylinder", label: "Cylinder", group: "Dimensional", cells: 4 },
  { id: "galaxy", label: "Galaxy", group: "Dimensional", cells: 6 },
  // ---- Neon ----
  { id: "neon-ring", label: "Neon Ring", group: "Neon", cells: 0 },
  { id: "neon-pulse", label: "Neon Pulse", group: "Neon", cells: 0 },
  { id: "neon-tube", label: "Neon Tube", group: "Neon", cells: 0 },
  { id: "neon-sign", label: "Neon Sign", group: "Neon", cells: 4 },
  { id: "laser", label: "Laser", group: "Neon", cells: 0 },
  { id: "light-trail", label: "Light Trail", group: "Neon", cells: 0 },
  { id: "neon-arc", label: "Neon Arc", group: "Neon", cells: 0 },
  { id: "plasma", label: "Plasma", group: "Neon", cells: 0 },
  { id: "strobe", label: "Strobe", group: "Neon", cells: 3 },
  { id: "glow-dots", label: "Glow Dots", group: "Neon", cells: 5 },
  { id: "retro-grid", label: "Retro Grid", group: "Neon", cells: 0 },
  { id: "firefly", label: "Firefly", group: "Neon", cells: 5 },
  // ---- Liquid ----
  { id: "liquid-fill", label: "Liquid Fill", group: "Liquid", cells: 2 },
  { id: "drip", label: "Drip", group: "Liquid", cells: 1 },
  { id: "metaball", label: "Metaball", group: "Liquid", cells: 2 },
  { id: "wave-tank", label: "Wave Tank", group: "Liquid", cells: 2 },
  { id: "ripple-pool", label: "Ripple Pool", group: "Liquid", cells: 3 },
  { id: "mercury", label: "Mercury", group: "Liquid", cells: 0 },
  { id: "lava", label: "Lava", group: "Liquid", cells: 3 },
  { id: "ink", label: "Ink", group: "Liquid", cells: 3 },
  { id: "splash", label: "Splash", group: "Liquid", cells: 3 },
  { id: "whirl", label: "Whirl", group: "Liquid", cells: 0 },
  { id: "pour", label: "Pour", group: "Liquid", cells: 2 },
  // ---- Glitch ----
  { id: "glitch-block", label: "Glitch Block", group: "Glitch", cells: 0 },
  { id: "glitch-text", label: "Glitch Text", group: "Glitch", cells: 3 },
  { id: "rgb-split", label: "RGB Split", group: "Glitch", cells: 3 },
  { id: "scanlines", label: "Scanlines", group: "Glitch", cells: 0 },
  { id: "static-noise", label: "Static", group: "Glitch", cells: 0 },
  { id: "datamosh", label: "Datamosh", group: "Glitch", cells: 5 },
  { id: "corrupt-bar", label: "Corrupt Bar", group: "Glitch", cells: 0 },
  { id: "signal-loss", label: "Signal Loss", group: "Glitch", cells: 4 },
  { id: "vhs", label: "VHS", group: "Glitch", cells: 0 },
  { id: "pixel-drift", label: "Pixel Drift", group: "Glitch", cells: 9 },
  { id: "terminal", label: "Terminal", group: "Glitch", cells: 2 },
  // ---- Particles ----
  { id: "confetti", label: "Confetti", group: "Particles", cells: 8 },
  { id: "firework", label: "Firework", group: "Particles", cells: 8 },
  { id: "snow", label: "Snow", group: "Particles", cells: 6 },
  { id: "embers", label: "Embers", group: "Particles", cells: 5 },
  { id: "starfield", label: "Starfield", group: "Particles", cells: 8 },
  { id: "dust", label: "Dust", group: "Particles", cells: 7 },
  { id: "burst", label: "Burst", group: "Particles", cells: 6 },
  { id: "swarm", label: "Swarm", group: "Particles", cells: 7 },
  { id: "rain", label: "Rain", group: "Particles", cells: 6 },
  { id: "magnet", label: "Magnet", group: "Particles", cells: 7 },
  { id: "nebula", label: "Nebula", group: "Particles", cells: 6 },
  // ---- Futuristic ----
  { id: "hud-ring", label: "HUD Ring", group: "Futuristic", cells: 2 },
  { id: "reactor", label: "Reactor", group: "Futuristic", cells: 3 },
  { id: "hologram", label: "Hologram", group: "Futuristic", cells: 3 },
  { id: "warp", label: "Warp", group: "Futuristic", cells: 4 },
  { id: "targeting", label: "Targeting", group: "Futuristic", cells: 4 },
  { id: "circuit", label: "Circuit", group: "Futuristic", cells: 3 },
  { id: "barcode", label: "Barcode", group: "Futuristic", cells: 0 },
  { id: "quantum", label: "Quantum", group: "Futuristic", cells: 6 },
  { id: "portal", label: "Portal", group: "Futuristic", cells: 0 },
  { id: "shield", label: "Shield", group: "Futuristic", cells: 2 },
  { id: "satellite", label: "Satellite", group: "Futuristic", cells: 3 },
  { id: "teleport", label: "Teleport", group: "Futuristic", cells: 6 },
  // ---- Elastic ----
  { id: "rubber-band", label: "Rubber Band", group: "Elastic", cells: 1 },
  { id: "bungee", label: "Bungee", group: "Elastic", cells: 1 },
  { id: "trampoline", label: "Trampoline", group: "Elastic", cells: 1 },
  { id: "wobble", label: "Wobble", group: "Elastic", cells: 0 },
  { id: "pogo", label: "Pogo", group: "Elastic", cells: 1 },
  { id: "elastic-bar", label: "Elastic Bar", group: "Elastic", cells: 0 },
  { id: "catapult", label: "Catapult", group: "Elastic", cells: 1 },
  { id: "yo-yo", label: "Yo-yo", group: "Elastic", cells: 1 },
  { id: "elastic-ring", label: "Elastic Ring", group: "Elastic", cells: 0 },
  { id: "snap-dots", label: "Snap Dots", group: "Elastic", cells: 2 },
  { id: "chain", label: "Chain", group: "Elastic", cells: 5 },
  // ---- Minimal ----
  { id: "hairline", label: "Hairline", group: "Minimal", cells: 0 },
  { id: "tick", label: "Tick", group: "Minimal", cells: 0 },
  { id: "quarter", label: "Quarter", group: "Minimal", cells: 0 },
  { id: "dot-fade", label: "Dot Fade", group: "Minimal", cells: 0 },
  { id: "underline", label: "Underline", group: "Minimal", cells: 0 },
  { id: "pill-swap", label: "Pill Swap", group: "Minimal", cells: 0 },
  { id: "bracket", label: "Bracket", group: "Minimal", cells: 2 },
  { id: "slash", label: "Slash", group: "Minimal", cells: 0 },
  { id: "micro-dots", label: "Micro Dots", group: "Minimal", cells: 3 },
  { id: "ring-thin", label: "Ring Thin", group: "Minimal", cells: 0 },
  { id: "crosshair", label: "Crosshair", group: "Minimal", cells: 0 },
  // ---- Gradient ----
  { id: "mesh", label: "Mesh", group: "Gradient", cells: 0 },
  { id: "hue-ring", label: "Hue Ring", group: "Gradient", cells: 0 },
  { id: "gradient-orb", label: "Gradient Orb", group: "Gradient", cells: 0 },
  { id: "chroma", label: "Chroma", group: "Gradient", cells: 3 },
  { id: "ombre", label: "Ombré", group: "Gradient", cells: 6 },
  { id: "iridescent", label: "Iridescent", group: "Gradient", cells: 0 },
  { id: "sunrise", label: "Sunrise", group: "Gradient", cells: 0 },
  { id: "refract", label: "Refract", group: "Gradient", cells: 3 },
  { id: "gradient-border", label: "Gradient Border", group: "Gradient", cells: 0 },
  { id: "color-cycle", label: "Color Cycle", group: "Gradient", cells: 0 },
  { id: "northern", label: "Northern", group: "Gradient", cells: 4 },
  // ---- Kinetic ----
  { id: "gears", label: "Gears", group: "Kinetic", cells: 2 },
  { id: "metronome", label: "Metronome", group: "Kinetic", cells: 1 },
  { id: "hourglass", label: "Hourglass", group: "Kinetic", cells: 3 },
  { id: "piston", label: "Piston", group: "Kinetic", cells: 1 },
  { id: "carousel", label: "Carousel", group: "Kinetic", cells: 5 },
  { id: "clockwork", label: "Clockwork", group: "Kinetic", cells: 3 },
  { id: "abacus", label: "Abacus", group: "Kinetic", cells: 3 },
  { id: "conveyor", label: "Conveyor", group: "Kinetic", cells: 3 },
  { id: "pie", label: "Pie", group: "Kinetic", cells: 0 },
  { id: "seesaw", label: "Seesaw", group: "Kinetic", cells: 1 },
  { id: "roller", label: "Roller", group: "Kinetic", cells: 2 },
  // ---- Premium ----
  { id: "logo-morph", label: "Logo Morph", group: "Premium", cells: 3 },
  { id: "card-stack", label: "Card Stack", group: "Premium", cells: 3 },
  { id: "progress-ring", label: "Progress Ring", group: "Premium", cells: 1 },
  { id: "pill-progress", label: "Pill Progress", group: "Premium", cells: 0 },
  { id: "glass-ring", label: "Glass Ring", group: "Premium", cells: 0 },
  { id: "orbit-avatar", label: "Orbit Avatar", group: "Premium", cells: 5 },
  { id: "checklist", label: "Checklist", group: "Premium", cells: 3 },
  { id: "upload-cloud", label: "Upload Cloud", group: "Premium", cells: 3 },
  { id: "sync", label: "Sync", group: "Premium", cells: 2 },
  { id: "steps", label: "Steps", group: "Premium", cells: 4 },
  { id: "spark-line", label: "Spark Line", group: "Premium", cells: 2 },
  // ---- Medical ----
  { id: "ecg", label: "ECG Monitor", group: "Medical", cells: 2 },
  { id: "vitals", label: "Vitals", group: "Medical", cells: 3 },
  { id: "lungs", label: "Lungs", group: "Medical", cells: 1 },
  { id: "capsule", label: "Capsule", group: "Medical", cells: 5 },
  { id: "syringe", label: "Syringe", group: "Medical", cells: 2 },
  { id: "microscope", label: "Microscope", group: "Medical", cells: 4 },
  { id: "cell-divide", label: "Cell Divide", group: "Medical", cells: 2 },
  { id: "blood-flow", label: "Blood Flow", group: "Medical", cells: 5 },
  // ---- Space ----
  { id: "black-hole", label: "Black Hole", group: "Space", cells: 0 },
  { id: "eclipse", label: "Eclipse", group: "Space", cells: 2 },
  { id: "star-birth", label: "Star Birth", group: "Space", cells: 5 },
  { id: "constellation", label: "Constellation", group: "Space", cells: 4 },
  { id: "meteor-shower", label: "Meteor Shower", group: "Space", cells: 5 },
  { id: "solar-system", label: "Solar System", group: "Space", cells: 3 },
  { id: "rocket", label: "Rocket", group: "Space", cells: 4 },
  { id: "pulsar", label: "Pulsar", group: "Space", cells: 2 },
  // ---- Nature ----
  { id: "bloom-flower", label: "Flower Bloom", group: "Nature", cells: 6 },
  { id: "sprout", label: "Sprout", group: "Nature", cells: 3 },
  { id: "tree-grow", label: "Tree Growth", group: "Nature", cells: 6 },
  { id: "smoke", label: "Smoke", group: "Nature", cells: 4 },
  { id: "tornado", label: "Tornado", group: "Nature", cells: 5 },
  { id: "wind", label: "Wind", group: "Nature", cells: 4 },
  { id: "butterfly", label: "Butterfly", group: "Nature", cells: 2 },
  { id: "honeycomb", label: "Honeycomb", group: "Nature", cells: 7 },
  { id: "rainbow", label: "Rainbow", group: "Nature", cells: 4 },
  // ---- Weather ----
  { id: "cloud-form", label: "Cloud Forming", group: "Weather", cells: 4 },
  { id: "storm", label: "Storm", group: "Weather", cells: 4 },
  { id: "fog", label: "Fog", group: "Weather", cells: 4 },
  { id: "sun-clouds", label: "Sun & Clouds", group: "Weather", cells: 3 },
  { id: "frost", label: "Frost", group: "Weather", cells: 6 },
  { id: "sunbeam", label: "Sunbeam", group: "Weather", cells: 0 },
  { id: "thermometer", label: "Thermometer", group: "Weather", cells: 2 },
  // ---- Technology ----
  { id: "battery", label: "Battery", group: "Technology", cells: 5 },
  { id: "wifi", label: "Wi-Fi", group: "Technology", cells: 3 },
  { id: "signal-tower", label: "Signal Tower", group: "Technology", cells: 3 },
  { id: "cpu", label: "CPU", group: "Technology", cells: 2 },
  { id: "server-rack", label: "Server Rack", group: "Technology", cells: 4 },
  { id: "packets", label: "Network Packets", group: "Technology", cells: 3 },
  { id: "data-transfer", label: "Data Transfer", group: "Technology", cells: 4 },
  { id: "hard-drive", label: "Hard Drive", group: "Technology", cells: 2 },
  { id: "power-plug", label: "Power Plug", group: "Technology", cells: 2 },
  // ---- AI ----
  { id: "neural-net", label: "Neural Net", group: "AI", cells: 7 },
  { id: "ai-think", label: "AI Thinking", group: "AI", cells: 3 },
  { id: "synapse", label: "Synapse", group: "AI", cells: 3 },
  { id: "ml-train", label: "Model Training", group: "AI", cells: 2 },
  { id: "token-stream", label: "Token Stream", group: "AI", cells: 7 },
  { id: "attention", label: "Attention", group: "AI", cells: 7 },
  { id: "robot-eyes", label: "Robot Eyes", group: "AI", cells: 2 },
  { id: "embedding", label: "Embedding", group: "AI", cells: 8 },
  // ---- Communication ----
  { id: "message-send", label: "Message Send", group: "Communication", cells: 3 },
  { id: "delivery-ticks", label: "Delivery Ticks", group: "Communication", cells: 3 },
  { id: "envelope", label: "Envelope", group: "Communication", cells: 3 },
  { id: "bell", label: "Notification Bell", group: "Communication", cells: 1 },
  { id: "chat-threads", label: "Chat Threads", group: "Communication", cells: 4 },
  { id: "voice-wave", label: "Voice Wave", group: "Communication", cells: 2 },
  { id: "mic-listen", label: "Microphone", group: "Communication", cells: 3 },
  { id: "translate", label: "Translate", group: "Communication", cells: 6 },
  // ---- Security ----
  { id: "padlock", label: "Padlock", group: "Security", cells: 2 },
  { id: "fingerprint", label: "Fingerprint", group: "Security", cells: 4 },
  { id: "face-scan", label: "Face Scan", group: "Security", cells: 2 },
  { id: "qr-scan", label: "QR Scan", group: "Security", cells: 4 },
  { id: "encrypt", label: "Encryption", group: "Security", cells: 6 },
  { id: "key-turn", label: "Key Turn", group: "Security", cells: 1 },
  { id: "otp-code", label: "OTP Code", group: "Security", cells: 4 },
  { id: "vault", label: "Vault Dial", group: "Security", cells: 2 },
  // ---- Developer ----
  { id: "code-compile", label: "Code Compile", group: "Developer", cells: 5 },
  { id: "git-branch", label: "Git Branch", group: "Developer", cells: 4 },
  { id: "pipeline", label: "Build Pipeline", group: "Developer", cells: 4 },
  { id: "npm-install", label: "Package Install", group: "Developer", cells: 5 },
  { id: "container", label: "Container", group: "Developer", cells: 4 },
  { id: "k8s-pods", label: "Pod Scaling", group: "Developer", cells: 6 },
  { id: "bug-fix", label: "Bug Fix", group: "Developer", cells: 5 },
  { id: "code-diff", label: "Code Diff", group: "Developer", cells: 5 },
  // ---- Data ----
  { id: "db-query", label: "Database Query", group: "Data", cells: 4 },
  { id: "db-sync", label: "Database Sync", group: "Data", cells: 4 },
  { id: "scatter-plot", label: "Scatter Plot", group: "Data", cells: 6 },
  { id: "spreadsheet", label: "Spreadsheet", group: "Data", cells: 16 },
  { id: "file-scan", label: "File Scan", group: "Data", cells: 4 },
  { id: "folder-scan", label: "Folder Scan", group: "Data", cells: 3 },
  { id: "cloud-sync", label: "Cloud Sync", group: "Data", cells: 4 },
  { id: "backup", label: "Backup", group: "Data", cells: 3 },
  { id: "data-funnel", label: "Data Funnel", group: "Data", cells: 5 },
  // ---- Finance ----
  { id: "payment-card", label: "Payment Card", group: "Finance", cells: 3 },
  { id: "coin-flip", label: "Coin Flip", group: "Finance", cells: 2 },
  { id: "cart", label: "Shopping Cart", group: "Finance", cells: 3 },
  { id: "receipt", label: "Receipt", group: "Finance", cells: 6 },
  { id: "stock-candles", label: "Stock Candles", group: "Finance", cells: 6 },
  { id: "money-transfer", label: "Money Transfer", group: "Finance", cells: 3 },
  // ---- Transport ----
  { id: "gps-locate", label: "GPS Locate", group: "Transport", cells: 3 },
  { id: "route-calc", label: "Route Calc", group: "Transport", cells: 4 },
  { id: "compass", label: "Compass", group: "Transport", cells: 1 },
  { id: "truck", label: "Delivery Truck", group: "Transport", cells: 3 },
  { id: "package-track", label: "Package Tracking", group: "Transport", cells: 5 },
  { id: "plane-path", label: "Flight Path", group: "Transport", cells: 1 },
  { id: "traffic-light", label: "Traffic Light", group: "Transport", cells: 3 },
  // ---- Food ----
  { id: "coffee-brew", label: "Coffee Brew", group: "Food", cells: 3 },
  { id: "oven-bake", label: "Oven Bake", group: "Food", cells: 3 },
  { id: "pizza-slices", label: "Pizza Slices", group: "Food", cells: 6 },
  { id: "pan-flip", label: "Pan Flip", group: "Food", cells: 1 },
  { id: "blender", label: "Blender", group: "Food", cells: 4 },
  { id: "toaster", label: "Toaster", group: "Food", cells: 2 },
  // ---- Creative ----
  { id: "pencil-draw", label: "Pencil Draw", group: "Creative", cells: 2 },
  { id: "brush-stroke", label: "Brush Stroke", group: "Creative", cells: 2 },
  { id: "palette", label: "Colour Palette", group: "Creative", cells: 5 },
  { id: "camera-focus", label: "Camera Focus", group: "Creative", cells: 6 },
  { id: "film-strip", label: "Film Strip", group: "Creative", cells: 3 },
  { id: "vinyl", label: "Vinyl Record", group: "Creative", cells: 1 },
  { id: "book-flip", label: "Book Flip", group: "Creative", cells: 3 },
  { id: "typeset", label: "Typeset", group: "Creative", cells: 6 },
  // ---- Physics ----
  { id: "magnetic-field", label: "Magnetic Field", group: "Physics", cells: 6 },
  { id: "lightning", label: "Lightning", group: "Physics", cells: 2 },
  { id: "electric-arc", label: "Electric Arc", group: "Physics", cells: 2 },
  { id: "gravity-well", label: "Gravity Well", group: "Physics", cells: 2 },
  { id: "interference", label: "Wave Interference", group: "Physics", cells: 4 },
  { id: "pendulum-wave", label: "Pendulum Wave", group: "Physics", cells: 7 },
  { id: "newton-disc", label: "Newton Disc", group: "Physics", cells: 0 },
  { id: "resonance", label: "Resonance", group: "Physics", cells: 3 },
  // ---- Gaming ----
  { id: "health-bar", label: "Health Bar", group: "Gaming", cells: 2 },
  { id: "dice-roll", label: "Dice Roll", group: "Gaming", cells: 4 },
  { id: "level-up", label: "Level Up", group: "Gaming", cells: 4 },
  { id: "coin-collect", label: "Coin Collect", group: "Gaming", cells: 3 },
  { id: "chomp", label: "Chomp", group: "Gaming", cells: 5 },
  { id: "sprite-march", label: "Sprite March", group: "Gaming", cells: 4 },
  { id: "mana-orb", label: "Mana Orb", group: "Gaming", cells: 3 },
] as const;

export const GROUPS = [
  { name: "Spinners", description: "Rings and arcs — the classic shape, modernised." },
  { name: "Dots", description: "Small, quiet, and good inline with text." },
  { name: "Bars", description: "Equalizer-style motion with a strong rhythm." },
  { name: "Shapes", description: "Geometry that morphs, folds, and turns." },
  { name: "Progress", description: "Wide, indeterminate tracks for page and upload states." },
  { name: "Grids", description: "Cell fields that pulse, flip, and cascade." },
  { name: "Pulses", description: "Expanding rings for live, waiting, or listening states." },
  { name: "Organic", description: "Playful, physical motion with personality." },
  { name: "Skeletons", description: "Content-shaped placeholders — use these over spinners for page loads." },
  { name: "Dimensional", description: "Depth, 3D rotation, and orbital motion." },
  { name: "Neon", description: "Light that hums, blooms, and flickers alight." },
  { name: "Liquid", description: "Fluid behaviour — filling, pouring, rippling, merging." },
  { name: "Glitch", description: "Digital damage: tearing, static, dropout, corruption." },
  { name: "Particles", description: "Fields of small things falling, bursting, drifting, swarming." },
  { name: "Futuristic", description: "Reticles, reactors, and hardware that does not exist yet." },
  { name: "Elastic", description: "Spring physics with genuine overshoot and recoil." },
  { name: "Minimal", description: "Quiet motion for dense UI, toolbars, and inline text." },
  { name: "Gradient", description: "Colour itself is the animation." },
  { name: "Kinetic", description: "Mechanisms — gears, cranks, belts, beams, and escapements." },
  { name: "Premium", description: "Product-grade motion for onboarding, uploads, and sync." },
  { name: "Medical", description: "Physiology, diagnostics and the clinic." },
  { name: "Space", description: "Astrophysics — discs, orbits, and things igniting." },
  { name: "Nature", description: "Growing, burning, blowing and blooming." },
  { name: "Weather", description: "Sky conditions, from a clear sun to a full storm." },
  { name: "Technology", description: "Hardware doing its job — power, radio, silicon, disks." },
  { name: "AI", description: "Models thinking: layers, signals, tokens and clusters." },
  { name: "Communication", description: "Messages leaving, arriving, and being understood." },
  { name: "Security", description: "Locks, scans and ciphers doing their checks." },
  { name: "Developer", description: "The inner loop: compile, branch, build, ship." },
  { name: "Data", description: "Stores queried, files parsed, records moved." },
  { name: "Finance", description: "Money changing hands and being checked." },
  { name: "Transport", description: "Getting there: fixes, routes, wheels and wings." },
  { name: "Food", description: "Things brewing, baking, tossing and popping." },
  { name: "Creative", description: "Studio tools: pencils, brushes, lenses and type." },
  { name: "Physics", description: "Fields, charge, gravity and standing waves." },
  { name: "Gaming", description: "HUD and pickup motion lifted from games." },
] as const;

export type LoaderVariant = (typeof VARIANTS)[number]["id"];
export type LoaderGroup = (typeof GROUPS)[number]["name"];
export type VariantMeta = (typeof VARIANTS)[number];
